# Default values for Healthmed.Doctor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: matheusaoc/healthmed-doctor
  pullPolicy: IfNotPresent
  tag: "0.0.1"

nameOverride: ""
fullnameOverride: ""
namespace: healthmed

podLabels: {}

replicas: 1

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 800Mi
  requests:
    cpu: 100m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /hc
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
readinessProbe:
  httpGet:
    path: /hc
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage:

nodeSelector: {}

configmap:
  mongodb:
    user: healthmed-doctors
    password: 1234
    cluster: healthmed/
    appName: healthmed
    database: healthmed-doctors