apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "healthmed.doctor.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "healthmed.doctor.labels" . | nindent 4 }}
data:
  MongoDb__ConnectionString: mongodb+srv://{{ .Values.configmap.mongodb.user }}:{{ .Values.configmap.mongodb.password }}@{{ .Values.configmap.mongodb.cluster }}?retryWrites=true&w=majority&appName={{ .Values.configmap.mongodb.appName }}
  MongoDb__Database: {{ .Values.configmap.mongodb.database }}
