apiVersion: v1
kind: Service
metadata:
  name: {{ include "healthmed.doctor.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "healthmed.doctor.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "service={{ include "healthmed.doctor.fullname" . }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "healthmed.doctor.selectorLabels" . | nindent 4 }}
